version: '3'
services:
  slave_1:
    image: world_slave
    volumes:
     - minecraft_world_playerdata:/world/playerdata
     - minecraft_world_data:/world/data
     - minecraft_world_region:/world/region
    ports:
     - 25565:25565
    environment:
     - PROXY_HOST=manager
     - PROXY_PORT=4441

  slave_2:
    image: world_slave
    volumes:
     - minecraft_world_playerdata:/world/playerdata
     - minecraft_world_data:/world/data
     - minecraft_world_region:/world/region
    ports:
     - 25566:25565
    environment:
     - PROXY_HOST=manager
     - PROXY_PORT=4441
  manager:
    image: chunky_manager
    ports:
      - 8080:8080
      - 80:80

  #slave_3:
  #  image: world_slave
  #  volumes:
  #   - minecraft_world_playerdata:/world/playerdata
  #   - minecraft_world_data:/world/data
  #   - minecraft_world_region:/world/region
  #  ports:
  #   - 25567:25565
  #  environment:
  #   - PROXY_HOST=manager
  #   - PROXY_PORT=4441
  #manager:
  #  image: chunky_manager

  proxy:
    image: bungee
    ports:
     - 4444:4444
    environment:
     - COORDINATOR_ADDR=manager
     - COORDINATOR_PORT=4440


volumes:
  minecraft_world_playerdata:
    external: true
  minecraft_world_data:
    external: true
  minecraft_world_region:
    external: true
